# Generated by Django 6.0.5 on 2026-05-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=120)),
                ('publication_year', models.IntegerField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
